time_to_answer/config/routes.rb
Rails.application.routes.draw do
  namespace :admins_backoffice do #List
  resources :admins
  resources :subjects
  resources :questions
  end

  namespace :users_backoffice do
  get 'welcome/index'
  resources :users
  end

  
  namespace :site do
  get 'welcome/index'
  end

  namespace :users_backoffice do
    get 'welcome/index'
  end
  devise_for :users

  namespace :admins_backoffice do
    get 'welcome/index' #inicio
  end

  devise_for :admins

  get 'inicio', to: 'site/welcome#index'
  
  root to: 'site/welcome#index' # Defiinindo rota padrão 

end

time_to_answer/app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :subject
end

time_to_answer/app/controllers/admins_backoffice/admins_controller.rb
class AdminsBackoffice::AdminsController < AdminsBackofficeController
  before_action :set_adm, only: [:show,:edit,:update,:destroy]
  before_action :pass_verify, only: [:update]
  before_action :admin_params, only: [:update, :create]
  def index
    @admins = Admin.all
  end

  def new
    @admin = Admin.new
  end

  def create
    @admin = Admin.new(admin_params)
    if @admin.save.inspect
      redirect_to admins_backoffice_admins_path , notice: "Adm criado com sucesso" 
    else
      if @admin.errors.any?
        @erros = @admin.errors.full_messages
        render :new
      end
    end
  end

  def edit 
    params[:id]# passo o parametro :id na url 
    #@admin = Admin.find(params[:id])#Busco pelo o id informado no banco
  end

  def destroy
      @admin.destroy
      redirect_to admins_backoffice_admins_path , notice: "Deletado com sucesso"
  end

  def update #Update
    #params_admin = params.require(:admin).permit(:email,:password,:password_confirmation)
    # Seto uma def que pegar o id private chamada admin_params e o parametro que passo pra ela é o hash :admin 
    #que está no form do edit.html
   
    if @admin.update(admin_params) # pego os dados  antigos da variavel admin e set os novos do form
      redirect_to admins_backoffice_admins_path , notice: "Alterações efetuadas com sucesso" #redireciono para a pag 
    else
      if @admin.errors.any?
        @erros = @admin.errors.full_messages
        render :edit
      end
    end
  end

  private

  def set_adm
    @admin = Admin.find(params[:id])
  end

  def admin_params
    params.require(:admin).permit(:email,:password,:password_confirmation) #pego o hash do form com id informado
  end

  def pass_verify
    if params[:admin][:password].blank? and params[:admin][:password_confirmation].blank?
      params[:admin].extract!(:password,:password_confirmation)
    end
  end

end

time_to_answer/app/controllers/admins_backoffice/questions_controller.rb
class AdminsBackoffice::QuestionsController < AdminsBackofficeController
    before_action :set_question, only: [:show,:edit,:update,:destroy]
    before_action :question_params, only: [:update, :create]
    before_action :set_type_question, only: [:edit,:new]
    def index
      @questions = Question.includes(:subject).all #Incluindo isso para evitar o n+1
    end
  
    def new
      @question = Question.new
    end
  
    def create
      @question = Question.new(question_params)
      if @question.save.inspect
        redirect_to admins_backoffice_questions_path , notice: "Assunto criado com sucesso" 
      else
        if @question.errors.any?
          @erros = @question.errors.full_messages
          render :new
        end
      end
    end
  
    def edit 
      params[:id]# passo o parametro :id na url 
      #@admin = Admin.find(params[:id])#Busco pelo o id informado no banco
    end
  
    def destroy
        @question.destroy
        redirect_to admins_backoffice_questions_path , notice: "Pergunta deletada com sucesso"
    end
  
    def update #Update
      #params_admin = params.require(:admin).permit(:email,:password,:password_confirmation)
      # Seto uma def que pegar o id private chamada admin_params e o parametro que passo pra ela é o hash :admin 
      #que está no form do edit.html
     
      if @question.update(question_params) # pego os dados  antigos da variavel admin e set os novos do form
        redirect_to admins_backoffice_questions_paths , notice: "Alterações efetuadas com sucesso" #redireciono para a pag 
      else
        if @question.errors.any?
          @erros = @question.errors.full_messages
          render :edit
        end
      end
    end
  
    private
  
    def set_question
      @question = Question.find(params[:id])
    end
  
    def question_params
      params.require(:question).permit(:description,:subject) #pego o hash do form com id informado
    end

    def set_type_question
      @set_type_question = Subject.all
    end
  
    
end

time_to_answer/app/controllers/admins_backoffice/subjects_controller.rb
class AdminsBackoffice::SubjectsController < AdminsBackofficeController
    before_action :set_sub, only: [:show,:edit,:update,:destroy]
    before_action :sub_params, only: [:update, :create]
    def index
      @subs = Subject.all
    end
  
    def new
      @sub = Subject.new
    end
  
    def create
      @sub = Subject.new(sub_params)
      if @sub.save.inspect
        redirect_to admins_backoffice_subjects_path , notice: "Assunto criado com sucesso" 
      else
        if @sub.errors.any?
          @erros = @sub.errors.full_messages
          render :new
        end
      end
    end
  
    def edit 
      params[:id]# passo o parametro :id na url 
      #@admin = Admin.find(params[:id])#Busco pelo o id informado no banco
    end
  
    def destroy
        @sub.destroy
        redirect_to admins_backoffice_subjects_path , notice: "Pergunta deletada com sucesso"
    end
  
    def update #Update
      #params_admin = params.require(:admin).permit(:email,:password,:password_confirmation)
      # Seto uma def que pegar o id private chamada admin_params e o parametro que passo pra ela é o hash :admin 
      #que está no form do edit.html
     
      if @sub.update(sub_params) # pego os dados  antigos da variavel admin e set os novos do form
        redirect_to admins_backoffice_subjects_path , notice: "Alterações efetuadas com sucesso" #redireciono para a pag 
      else
        if @sub.errors.any?
          @erros = @sub.errors.full_messages
          render :edit
        end
      end
    end
  
    private
  
    def set_sub
      @sub = Subject.find(params[:id])
    end
  
    def sub_params
      params.require(:sub).permit(:description) #pego o hash do form com id informado
    end
  
    
end

time_to_answer/app/controllers/admins_backoffice/welcome_controller.rb
class AdminsBackoffice::WelcomeController < AdminsBackofficeController
  def index
  end
end

time_to_answer/app/controllers/admins_backoffice_controller.rb
class AdminsBackofficeController < ApplicationController
    before_action :authenticate_admin!
    layout 'admins_backoffice'
end

time_to_answer/app/helpers/admins_backoffice/admins_helper.rb
module AdminsBackoffice::AdminsHelper
end

time_to_answer/app/helpers/admins_backoffice/questions_helper.rb
module AdminsBackoffice::QuestionsHelper
end

time_to_answer/app/helpers/admins_backoffice/subjects_helper.rb
module AdminsBackoffice::SubjectsHelper
end

time_to_answer/app/helpers/admins_backoffice/welcome_helper.rb
module AdminsBackoffice::WelcomeHelper
end

time_to_answer/app/helpers/admins_backoffice_helper.rb
module AdminsBackofficeHelper
    def translate_attribute(object = nil, method= nil)
        # (object && method ) ? object.model.human_attribute_name(method) : "Informe os parametros corretamente"
        #Ternario A cima
        
        if object and method
            object.model.human_attribute_name(method)
        else
            "Informe os parametros corretamente"
        end
    end
end

time_to_answer/app/views/admins_backoffice/questions/edit.html.erb
<%#= @admin.inspect%>
<%if @erros != nil%>
    <%for erro in @erros %>
        <div class="alert alert-danger" role="alert">
            <ul>
                <li><%=erro%></li>
            </ul>
        </div>
    <%end%>
<%end%>
<%= form_for :question,url: "/admins_backoffice/questions/#{@question.id}", method: "PATCH" do |f|%>
<%#= form_for(@question) do |form|%>
    <div class="form-group">
        <%=f.label :description%>
        <%=f.text_area (:description),placeholder: "Email",class:"form-control" %>
    </div>
    <div class="form-group">
        <%=f.label :subject %>
        <%=f.collection_select(:subject_id,@set_type_question,:id,:description,class:"form-control")%>
    </div>
    <div class="actions">
        <%=f.submit nil,class:"btn btn-primary" %>
    </div>

<%end%>

time_to_answer/app/views/admins_backoffice/questions/index.html.erb
<h1><%=t('messages.listign_questions')%></h1>
 <table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col"><%=translate_attribute(@questions,:description)%></th>
      <th scope="col"><%=translate_attribute(@questions, :subject)%></th>
      <th><%= link_to "+",new_admins_backoffice_question_path, class:"btn btn-success btn-circle"%></tr>
  </thead>
  <%for info in @questions%>
    <tbody>
        <tr>
        <th scope="row"><%=info.id%></th>
        <td><%=info.description%></td>
        <td><%=info.subject.description%></td>
        <td >
        <%= link_to "O",edit_admins_backoffice_question_path(info), class:"btn btn-success btn-circle"%>
        
        <%= link_to "x","/admins_backoffice/questions/#{info.id}" ,method: :delete, class:"btn btn-danger btn-circle",data:{confirm: t('messages.sure')}%>
        </td>
        </tr>
    </tbody>
  <%end%>
  
</table>

time_to_answer/app/views/admins_backoffice/questions/new.html.erb
<%if @erros != nil%>
    <%for erro in @erros %>
        <div class="alert alert-danger" role="alert">
            <ul>
                <li><%=erro%></li>
            </ul>
        </div>
    <%end%>
<%end%>
<%= form_for :question,url: "/admins_backoffice/questions/#{@question.id}", method: "POST" do |f|%>

    <div class="form-group">
        <%=f.label :description %>
        <%=f.text_area (:description),placeholder: "Tema",class:"form-control" %>
    </div>
    <div class="form-group">
        <%=f.label :subject %>
        <%=f.collection_select(:subject_id,@set_type_question,:id,:description,class:"form-control")%>
    </div>
    
    <div class="actions">
        <%=f.submit nil,class:"btn btn-primary" %>
    </div>

<%end%>