time_to_answer/config/routes.rb
Rails.application.routes.draw do
  namespace :admins_backoffice do #List
  resources :admins
  resources :subjects
  resources :questions
  end

  namespace :users_backoffice do
  get 'welcome/index'
  resources :users
  end

  
  namespace :site do
  get 'welcome/index'
  end

  namespace :users_backoffice do
    get 'welcome/index'
  end
  devise_for :users

  namespace :admins_backoffice do
    get 'welcome/index' #inicio
  end

  devise_for :admins

  get 'inicio', to: 'site/welcome#index'
  
  root to: 'site/welcome#index' # Defiinindo rota padrão 

end

time_to_answer/app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

time_to_answer/app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
end

time_to_answer/app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :subject
end

time_to_answer/app/models/subject.rb
class Subject < ActiveRecord::Base
    has_many :questions
    
end

time_to_answer/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

time_to_answer/app/controllers/admins_backoffice_controller.rb
class AdminsBackofficeController < ApplicationController
    before_action :authenticate_admin!
    layout 'admins_backoffice'
end

time_to_answer/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

time_to_answer/app/controllers/site/welcome_controller.rb
class Site::WelcomeController < SiteController
  def index
  end
end

time_to_answer/app/controllers/site_controller.rb
class SiteController < ApplicationController
    layout 'site'
end

time_to_answer/app/controllers/users_backoffice_controller.rb
class UsersBackofficeController < ApplicationController
    before_action :authenticate_user!
    layout 'users_backoffice'
end

time_to_answer/app/helpers/admins_backoffice/admins_helper.rb
module AdminsBackoffice::AdminsHelper
end

time_to_answer/app/helpers/admins_backoffice/questions_helper.rb
module AdminsBackoffice::QuestionsHelper
end

time_to_answer/app/helpers/admins_backoffice/subjects_helper.rb
module AdminsBackoffice::SubjectsHelper
end

time_to_answer/app/helpers/admins_backoffice/welcome_helper.rb
module AdminsBackoffice::WelcomeHelper
end

time_to_answer/app/helpers/admins_backoffice_helper.rb
module AdminsBackofficeHelper
    def translate_attribute(object = nil, method= nil)
        # (object && method ) ? object.model.human_attribute_name(method) : "Informe os parametros corretamente"
        #Ternario A cima
        
        if object and method
            object.model.human_attribute_name(method)
        else
            "Informe os parametros corretamente"
        end
    end
end

time_to_answer/app/helpers/application_helper.rb
module ApplicationHelper
end

time_to_answer/app/helpers/site/welcome_helper.rb
module Site::WelcomeHelper
end

time_to_answer/app/helpers/site_helper.rb
module SiteHelper
end

time_to_answer/app/helpers/users_backoffice/welcome_helper.rb
module UsersBackoffice::WelcomeHelper
end

time_to_answer/app/helpers/users_backoffice_helper.rb
module UsersBackofficeHelper
end

time_to_answer/app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

time_to_answer/app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

time_to_answer/app/views/admins_backoffice/admins/shared/_form.html.erb
<!--Funcionaria se o rails fosse a versão certa-->
<%if @erros != nil%>
<%for erro in @erros %>
    <div class="alert alert-danger" role="alert">
        <ul>
            <li><%=erro%></li>
        </ul>
    </div>
<%end%>
<%end%>
<%= form_for :admin,url: "/admins_backoffice/admins/#{@admin.id}", method: "POST" do |f|%>

<div class"form-group"">
    <%=f.label :email %>
    <%=f.text_field (:email),placeholder: "Email",class:"form-control" %>
</div>
<div class"form-group"">
    <%=f.label :password %>
    <%=f.password_field (:password), placeholder: "Senha",class:"form-control"%>
</div>
<div class"form-group"">
    <%=f.label :password_confirmation %>
    <%=f.password_field (:password_confirmation), placeholder: "Confirmação De Senha",class:"form-control" %>
</div>
<div class="actions">
    <%=f.submit nil,class:"btn btn-primary" %>
</div>
<!--
    <label for="exampleInputEmail1"><strong>Email</strong></label>
    <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" value='<%=@admin.email%>'>
</div>
<div class="form-group">
    <label for="exampleInputEmail1"><strong>Senha</strong></label>
    <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" value='<%=@admin.email%>'>
</div>
<div class="form-group">
    <label for="exampleInputEmail1"><strong>Confirmar senha!</strong></label>
    <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" value='<%=@admin.email%>'>
</div>

<button type="submit" class="btn btn-primary" method="post">Editar</button>-->
<%end%>

time_to_answer/app/views/layouts/admins_backoffice.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>TimeToAnswer</title>

    <%= stylesheet_link_tag    'application'%>
    <%= javascript_include_tag 'application'%> 
    <%= stylesheet_link_tag    'admins_backoffice'%>
    <%= javascript_include_tag 'admins_backoffice'%>
    
  <%= csrf_meta_tags %>

</head>

<body id="page-top">

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
        <div class="sidebar-brand-icon rotate-n-15">
          <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">BackOficce Admin <sup>2</sup></div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Dashboard -->
      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">
        Administrar
      </div>

      <!-- Nav Item - Pages Collapse Menu -->
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
          <i class="fas fa-fw fa-cog"></i>
          <span>Menu do Administrador</span>
        </a>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Custom Components:</h6>
            <%= link_to "Pagina Inicial",admins_backoffice_welcome_index_path,class:"collapse-item"%>
            <%= link_to "Listar Todos",admins_backoffice_admins_path,class:"collapse-item"%>
            <%= link_to "Assuntos",admins_backoffice_subjects_path,class:"collapse-item"%>
            <%= link_to "Questões",admins_backoffice_questions_path,class:"collapse-item"%>
          </div>
        </div>
      </li>
      <!-- Nav Item - Utilities Collapse Menu -->
      <!-- Divider -->
      <hr class="sidebar-divider">
      <!-- Heading -->
      <!-- Divider -->
    </ul>
    <!-- End of Sidebar -->
    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

          <!-- Sidebar Toggle (Topbar) -->
          <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
          </button>

          <!-- Topbar Search -->
          <!-- Topbar Navbar -->
          <ul class="navbar-nav ml-auto">

            <!-- Nav Item - Search Dropdown (Visible Only XS) -->
            <li class="nav-item dropdown no-arrow d-sm-none">
              <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw"></i>
              </a>
              <!-- Dropdown - Messages -->
              <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
                <form class="form-inline mr-auto w-100 navbar-search">
                  <div class="input-group">
                    <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                    <div class="input-group-append">
                      <button class="btn btn-primary" type="button">
                        <i class="fas fa-search fa-sm"></i>
                      </button>
                    </div>
                  </div>
                </form>
              </div>
            </li>

            <!-- Nav Item - Alerts -->
            <li class="nav-item dropdown no-arrow mx-1">
              <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                
              </a>
              <!-- Dropdown - Alerts -->
              <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="alertsDropdown">
                
              </div>
            </li>           

            <div class="topbar-divider d-none d-sm-block"></div>

            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
              <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">Valerie Luna</span>
                <img class="img-profile rounded-circle" src="https://source.unsplash.com/QAB-WJcbgJk/60x60">
              </a>
              <!-- Dropdown - User Information -->
              <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
            
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                  
                  <%= link_to destroy_admin_session_path, method: :delete do %>
                       <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>Deslogar
              
                  <%end%>
                  
                </a>
              </div>
            </li>

          </ul>

        </nav>
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        <div class="container-fluid">

          <!-- Page Heading -->
          <h1 class="h3 mb-4 text-gray-800">ADM</h1>
          <%= yield %>

        </div>
        <!-- /.container-fluid -->

      </div>
      <!-- End of Main Content -->

      <!-- Footer -->
      <footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Copyright &copy; Your Website 2019</span>
          </div>
        </div>
      </footer>
      <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
 

  <%if notice %>
    <script>
      $.bootstrapGrowl("<%=notice%>",{
        type: 'success',offset:{from:'top',amount: 20},align: 'right',width: 250, delay:4000,allow_dismiss:true,stackup_spacing: 10
      })
    </script>
  <%end%>
</body>

</html>

time_to_answer/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TimeToAnswer</title>
    <%= stylesheet_link_tag    'application'%>
    <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

time_to_answer/app/views/layouts/site.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TimeToAnswer</title>
    <%= stylesheet_link_tag    'application'%>
    <%= javascript_include_tag 'application'%>  
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

time_to_answer/app/views/layouts/users_backoffice.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>TimeToAnswer</title>

    <%= stylesheet_link_tag    'application'%>
    <%= javascript_include_tag 'application'%> 
    <%= stylesheet_link_tag    'admins_backoffice'%>
    <%= javascript_include_tag 'admins_backoffice'%>
    
  <%= csrf_meta_tags %>

</head>

<body id="page-top">

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
        <div class="sidebar-brand-icon rotate-n-15">
          <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">BackOficce Admin <sup>2</sup></div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Dashboard -->
      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">
        Administrar
      </div>

      <!-- Nav Item - Pages Collapse Menu -->
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
          <i class="fas fa-fw fa-cog"></i>
          <span>Menu do Administrador</span>
        </a>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Custom Components:</h6>
            <%= link_to "Pagina Inicial",users_backoffice_welcome_index_path,class:"collapse-item"%>
            <%= link_to "Listar Todos",users_backoffice_user_path,class:"collapse-item"%>
          </div>
        </div>
      </li>
      <!-- Nav Item - Utilities Collapse Menu -->
      <!-- Divider -->
      <hr class="sidebar-divider">
      <!-- Heading -->
      <!-- Divider -->
    </ul>
    <!-- End of Sidebar -->
    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

          <!-- Sidebar Toggle (Topbar) -->
          <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
          </button>

          <!-- Topbar Search -->
          <!-- Topbar Navbar -->
          <ul class="navbar-nav ml-auto">

            <!-- Nav Item - Search Dropdown (Visible Only XS) -->
            <li class="nav-item dropdown no-arrow d-sm-none">
              <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw"></i>
              </a>
              <!-- Dropdown - Messages -->
              <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
                <form class="form-inline mr-auto w-100 navbar-search">
                  <div class="input-group">
                    <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                    <div class="input-group-append">
                      <button class="btn btn-primary" type="button">
                        <i class="fas fa-search fa-sm"></i>
                      </button>
                    </div>
                  </div>
                </form>
              </div>
            </li>

            <!-- Nav Item - Alerts -->
            <li class="nav-item dropdown no-arrow mx-1">
              <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                
              </a>
              <!-- Dropdown - Alerts -->
              <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="alertsDropdown">
                
              </div>
            </li>           

            <div class="topbar-divider d-none d-sm-block"></div>

            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
              <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">Valerie Luna</span>
                <img class="img-profile rounded-circle" src="https://source.unsplash.com/QAB-WJcbgJk/60x60">
              </a>
              <!-- Dropdown - User Information -->
              <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
            
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                  
                  <%= link_to destroy_admin_session_path, method: :delete do %>
                       <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>Deslogar
              
                  <%end%>
                  
                </a>
              </div>
            </li>

          </ul>

        </nav>
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        <div class="container-fluid">

          <!-- Page Heading -->
          <h1 class="h3 mb-4 text-gray-800">ADM</h1>
          <%= yield %>

        </div>
        <!-- /.container-fluid -->

      </div>
      <!-- End of Main Content -->

      <!-- Footer -->
      <footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Copyright &copy; Your Website 2019</span>
          </div>
        </div>
      </footer>
      <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
 

  <%if notice %>
    <script>
      $.bootstrapGrowl("<%=notice%>",{
        type: 'success',offset:{from:'top',amount: 20},align: 'right',width: 250, delay:4000,allow_dismiss:true,stackup_spacing: 10
      })
    </script>
  <%end%>
</body>

</html>